version: "3"
services:
    core_api:
        build: .
        container_name: "core-api-container"
        ports:
            - "8000:15400"
        volumes:
            - ./app/:/app
        environment:
            - DB_HOST=db
            - DB_NAME=postgres_app
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
        depends_on: 
            - db
    db:
        image: postgres:10-alpine
        container_name: "postgres-container"
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres_app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
volumes:
    postgres-data: 